CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price INT,
    image_url VARCHAR(1000)
);

CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE wish (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_id   BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    CONSTRAINT fk_wish_member  FOREIGN KEY (member_id)  REFERENCES member(id),
    CONSTRAINT fk_wish_product FOREIGN KEY (product_id) REFERENCES products(id)
);
